//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korisnik.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korisnik", Namespace="http://schemas.datacontract.org/2004/07/KnjizaraServisHost")]
    [System.SerializableAttribute()]
    public partial class Korisnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_korisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Korisnicko_imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LozinkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Korisnik.ServiceReference1.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_korisnika {
            get {
                return this.Id_korisnikaField;
            }
            set {
                if ((this.Id_korisnikaField.Equals(value) != true)) {
                    this.Id_korisnikaField = value;
                    this.RaisePropertyChanged("Id_korisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Korisnicko_ime {
            get {
                return this.Korisnicko_imeField;
            }
            set {
                if ((object.ReferenceEquals(this.Korisnicko_imeField, value) != true)) {
                    this.Korisnicko_imeField = value;
                    this.RaisePropertyChanged("Korisnicko_ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka {
            get {
                return this.LozinkaField;
            }
            set {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true)) {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Korisnik.ServiceReference1.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/KnjizaraServisHost")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        korisnik = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        operater = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Knjiga", Namespace="http://schemas.datacontract.org/2004/07/KnjizaraServisHost.Klase")]
    [System.SerializableAttribute()]
    public partial class Knjiga : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_knjigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PopustField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_knjige {
            get {
                return this.Id_knjigeField;
            }
            set {
                if ((this.Id_knjigeField.Equals(value) != true)) {
                    this.Id_knjigeField = value;
                    this.RaisePropertyChanged("Id_knjige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Popust {
            get {
                return this.PopustField;
            }
            set {
                if ((this.PopustField.Equals(value) != true)) {
                    this.PopustField = value;
                    this.RaisePropertyChanged("Popust");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Porudzbine", Namespace="http://schemas.datacontract.org/2004/07/KnjizaraServisHost.Klase")]
    [System.SerializableAttribute()]
    public partial class Porudzbine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_knjigeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_korisnikaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_porudzbineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_knjige {
            get {
                return this.Id_knjigeField;
            }
            set {
                if ((this.Id_knjigeField.Equals(value) != true)) {
                    this.Id_knjigeField = value;
                    this.RaisePropertyChanged("Id_knjige");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_korisnika {
            get {
                return this.Id_korisnikaField;
            }
            set {
                if ((this.Id_korisnikaField.Equals(value) != true)) {
                    this.Id_korisnikaField = value;
                    this.RaisePropertyChanged("Id_korisnika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_porudzbine {
            get {
                return this.Id_porudzbineField;
            }
            set {
                if ((this.Id_porudzbineField.Equals(value) != true)) {
                    this.Id_porudzbineField = value;
                    this.RaisePropertyChanged("Id_porudzbine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKorisnik")]
    public interface IKorisnik {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrijava/Prijava", ReplyAction="http://tempuri.org/IPrijava/PrijavaResponse")]
        Korisnik.ServiceReference1.Korisnik Prijava(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrijava/Prijava", ReplyAction="http://tempuri.org/IPrijava/PrijavaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik> PrijavaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/SveKnjige", ReplyAction="http://tempuri.org/IKorisnik/SveKnjigeResponse")]
        Korisnik.ServiceReference1.Knjiga[] SveKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/SveKnjige", ReplyAction="http://tempuri.org/IKorisnik/SveKnjigeResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Knjiga[]> SveKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PorudzbineKorisnika", ReplyAction="http://tempuri.org/IKorisnik/PorudzbineKorisnikaResponse")]
        Korisnik.ServiceReference1.Porudzbine[] PorudzbineKorisnika(string id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PorudzbineKorisnika", ReplyAction="http://tempuri.org/IKorisnik/PorudzbineKorisnikaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PorudzbineKorisnikaAsync(string id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PoruciKnjigu", ReplyAction="http://tempuri.org/IKorisnik/PoruciKnjiguResponse")]
        void PoruciKnjigu(Korisnik.ServiceReference1.Porudzbine p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PoruciKnjigu", ReplyAction="http://tempuri.org/IKorisnik/PoruciKnjiguResponse")]
        System.Threading.Tasks.Task PoruciKnjiguAsync(Korisnik.ServiceReference1.Porudzbine p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKorisnikChannel : Korisnik.ServiceReference1.IKorisnik, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KorisnikClient : System.ServiceModel.ClientBase<Korisnik.ServiceReference1.IKorisnik>, Korisnik.ServiceReference1.IKorisnik {
        
        public KorisnikClient() {
        }
        
        public KorisnikClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KorisnikClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KorisnikClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KorisnikClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Korisnik.ServiceReference1.Korisnik Prijava(string username, string password) {
            return base.Channel.Prijava(username, password);
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik> PrijavaAsync(string username, string password) {
            return base.Channel.PrijavaAsync(username, password);
        }
        
        public Korisnik.ServiceReference1.Knjiga[] SveKnjige() {
            return base.Channel.SveKnjige();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Knjiga[]> SveKnjigeAsync() {
            return base.Channel.SveKnjigeAsync();
        }
        
        public Korisnik.ServiceReference1.Porudzbine[] PorudzbineKorisnika(string id_korisnika) {
            return base.Channel.PorudzbineKorisnika(id_korisnika);
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PorudzbineKorisnikaAsync(string id_korisnika) {
            return base.Channel.PorudzbineKorisnikaAsync(id_korisnika);
        }
        
        public void PoruciKnjigu(Korisnik.ServiceReference1.Porudzbine p) {
            base.Channel.PoruciKnjigu(p);
        }
        
        public System.Threading.Tasks.Task PoruciKnjiguAsync(Korisnik.ServiceReference1.Porudzbine p) {
            return base.Channel.PoruciKnjiguAsync(p);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOperater")]
    public interface IOperater {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrijava/Prijava", ReplyAction="http://tempuri.org/IPrijava/PrijavaResponse")]
        Korisnik.ServiceReference1.Korisnik Prijava(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrijava/Prijava", ReplyAction="http://tempuri.org/IPrijava/PrijavaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik> PrijavaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/SveKnjige", ReplyAction="http://tempuri.org/IKorisnik/SveKnjigeResponse")]
        Korisnik.ServiceReference1.Knjiga[] SveKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/SveKnjige", ReplyAction="http://tempuri.org/IKorisnik/SveKnjigeResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Knjiga[]> SveKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PorudzbineKorisnika", ReplyAction="http://tempuri.org/IKorisnik/PorudzbineKorisnikaResponse")]
        Korisnik.ServiceReference1.Porudzbine[] PorudzbineKorisnika(string id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PorudzbineKorisnika", ReplyAction="http://tempuri.org/IKorisnik/PorudzbineKorisnikaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PorudzbineKorisnikaAsync(string id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PoruciKnjigu", ReplyAction="http://tempuri.org/IKorisnik/PoruciKnjiguResponse")]
        void PoruciKnjigu(Korisnik.ServiceReference1.Porudzbine p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PoruciKnjigu", ReplyAction="http://tempuri.org/IKorisnik/PoruciKnjiguResponse")]
        System.Threading.Tasks.Task PoruciKnjiguAsync(Korisnik.ServiceReference1.Porudzbine p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKnjigu", ReplyAction="http://tempuri.org/IOperater/UnesiKnjiguResponse")]
        void UnesiKnjigu(Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKnjigu", ReplyAction="http://tempuri.org/IOperater/UnesiKnjiguResponse")]
        System.Threading.Tasks.Task UnesiKnjiguAsync(Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKorisnika", ReplyAction="http://tempuri.org/IOperater/UnesiKorisnikaResponse")]
        void UnesiKorisnika(Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKorisnika", ReplyAction="http://tempuri.org/IOperater/UnesiKorisnikaResponse")]
        System.Threading.Tasks.Task UnesiKorisnikaAsync(Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKnjigu", ReplyAction="http://tempuri.org/IOperater/IzmeniKnjiguResponse")]
        bool IzmeniKnjigu(int id_knjige, Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKnjigu", ReplyAction="http://tempuri.org/IOperater/IzmeniKnjiguResponse")]
        System.Threading.Tasks.Task<bool> IzmeniKnjiguAsync(int id_knjige, Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKorisnika", ReplyAction="http://tempuri.org/IOperater/IzmeniKorisnikaResponse")]
        bool IzmeniKorisnika(int id_korisnika, Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKorisnika", ReplyAction="http://tempuri.org/IOperater/IzmeniKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> IzmeniKorisnikaAsync(int id_korisnika, Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PregledPorudzbina", ReplyAction="http://tempuri.org/IOperater/PregledPorudzbinaResponse")]
        Korisnik.ServiceReference1.Porudzbine[] PregledPorudzbina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PregledPorudzbina", ReplyAction="http://tempuri.org/IOperater/PregledPorudzbinaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PregledPorudzbinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/SviKorisnici", ReplyAction="http://tempuri.org/IOperater/SviKorisniciResponse")]
        Korisnik.ServiceReference1.Korisnik[] SviKorisnici();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/SviKorisnici", ReplyAction="http://tempuri.org/IOperater/SviKorisniciResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik[]> SviKorisniciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PostaviPopust", ReplyAction="http://tempuri.org/IOperater/PostaviPopustResponse")]
        bool PostaviPopust(int id_knjige, float popust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PostaviPopust", ReplyAction="http://tempuri.org/IOperater/PostaviPopustResponse")]
        System.Threading.Tasks.Task<bool> PostaviPopustAsync(int id_knjige, float popust);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperaterChannel : Korisnik.ServiceReference1.IOperater, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperaterClient : System.ServiceModel.ClientBase<Korisnik.ServiceReference1.IOperater>, Korisnik.ServiceReference1.IOperater {
        
        public OperaterClient() {
        }
        
        public OperaterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperaterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Korisnik.ServiceReference1.Korisnik Prijava(string username, string password) {
            return base.Channel.Prijava(username, password);
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik> PrijavaAsync(string username, string password) {
            return base.Channel.PrijavaAsync(username, password);
        }
        
        public Korisnik.ServiceReference1.Knjiga[] SveKnjige() {
            return base.Channel.SveKnjige();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Knjiga[]> SveKnjigeAsync() {
            return base.Channel.SveKnjigeAsync();
        }
        
        public Korisnik.ServiceReference1.Porudzbine[] PorudzbineKorisnika(string id_korisnika) {
            return base.Channel.PorudzbineKorisnika(id_korisnika);
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PorudzbineKorisnikaAsync(string id_korisnika) {
            return base.Channel.PorudzbineKorisnikaAsync(id_korisnika);
        }
        
        public void PoruciKnjigu(Korisnik.ServiceReference1.Porudzbine p) {
            base.Channel.PoruciKnjigu(p);
        }
        
        public System.Threading.Tasks.Task PoruciKnjiguAsync(Korisnik.ServiceReference1.Porudzbine p) {
            return base.Channel.PoruciKnjiguAsync(p);
        }
        
        public void UnesiKnjigu(Korisnik.ServiceReference1.Knjiga k) {
            base.Channel.UnesiKnjigu(k);
        }
        
        public System.Threading.Tasks.Task UnesiKnjiguAsync(Korisnik.ServiceReference1.Knjiga k) {
            return base.Channel.UnesiKnjiguAsync(k);
        }
        
        public void UnesiKorisnika(Korisnik.ServiceReference1.Korisnik k) {
            base.Channel.UnesiKorisnika(k);
        }
        
        public System.Threading.Tasks.Task UnesiKorisnikaAsync(Korisnik.ServiceReference1.Korisnik k) {
            return base.Channel.UnesiKorisnikaAsync(k);
        }
        
        public bool IzmeniKnjigu(int id_knjige, Korisnik.ServiceReference1.Knjiga k) {
            return base.Channel.IzmeniKnjigu(id_knjige, k);
        }
        
        public System.Threading.Tasks.Task<bool> IzmeniKnjiguAsync(int id_knjige, Korisnik.ServiceReference1.Knjiga k) {
            return base.Channel.IzmeniKnjiguAsync(id_knjige, k);
        }
        
        public bool IzmeniKorisnika(int id_korisnika, Korisnik.ServiceReference1.Korisnik k) {
            return base.Channel.IzmeniKorisnika(id_korisnika, k);
        }
        
        public System.Threading.Tasks.Task<bool> IzmeniKorisnikaAsync(int id_korisnika, Korisnik.ServiceReference1.Korisnik k) {
            return base.Channel.IzmeniKorisnikaAsync(id_korisnika, k);
        }
        
        public Korisnik.ServiceReference1.Porudzbine[] PregledPorudzbina() {
            return base.Channel.PregledPorudzbina();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PregledPorudzbinaAsync() {
            return base.Channel.PregledPorudzbinaAsync();
        }
        
        public Korisnik.ServiceReference1.Korisnik[] SviKorisnici() {
            return base.Channel.SviKorisnici();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik[]> SviKorisniciAsync() {
            return base.Channel.SviKorisniciAsync();
        }
        
        public bool PostaviPopust(int id_knjige, float popust) {
            return base.Channel.PostaviPopust(id_knjige, popust);
        }
        
        public System.Threading.Tasks.Task<bool> PostaviPopustAsync(int id_knjige, float popust) {
            return base.Channel.PostaviPopustAsync(id_knjige, popust);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrijava/Prijava", ReplyAction="http://tempuri.org/IPrijava/PrijavaResponse")]
        Korisnik.ServiceReference1.Korisnik Prijava(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrijava/Prijava", ReplyAction="http://tempuri.org/IPrijava/PrijavaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik> PrijavaAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/SveKnjige", ReplyAction="http://tempuri.org/IKorisnik/SveKnjigeResponse")]
        Korisnik.ServiceReference1.Knjiga[] SveKnjige();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/SveKnjige", ReplyAction="http://tempuri.org/IKorisnik/SveKnjigeResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Knjiga[]> SveKnjigeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PorudzbineKorisnika", ReplyAction="http://tempuri.org/IKorisnik/PorudzbineKorisnikaResponse")]
        Korisnik.ServiceReference1.Porudzbine[] PorudzbineKorisnika(string id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PorudzbineKorisnika", ReplyAction="http://tempuri.org/IKorisnik/PorudzbineKorisnikaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PorudzbineKorisnikaAsync(string id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PoruciKnjigu", ReplyAction="http://tempuri.org/IKorisnik/PoruciKnjiguResponse")]
        void PoruciKnjigu(Korisnik.ServiceReference1.Porudzbine p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKorisnik/PoruciKnjigu", ReplyAction="http://tempuri.org/IKorisnik/PoruciKnjiguResponse")]
        System.Threading.Tasks.Task PoruciKnjiguAsync(Korisnik.ServiceReference1.Porudzbine p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKnjigu", ReplyAction="http://tempuri.org/IOperater/UnesiKnjiguResponse")]
        void UnesiKnjigu(Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKnjigu", ReplyAction="http://tempuri.org/IOperater/UnesiKnjiguResponse")]
        System.Threading.Tasks.Task UnesiKnjiguAsync(Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKorisnika", ReplyAction="http://tempuri.org/IOperater/UnesiKorisnikaResponse")]
        void UnesiKorisnika(Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/UnesiKorisnika", ReplyAction="http://tempuri.org/IOperater/UnesiKorisnikaResponse")]
        System.Threading.Tasks.Task UnesiKorisnikaAsync(Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKnjigu", ReplyAction="http://tempuri.org/IOperater/IzmeniKnjiguResponse")]
        bool IzmeniKnjigu(int id_knjige, Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKnjigu", ReplyAction="http://tempuri.org/IOperater/IzmeniKnjiguResponse")]
        System.Threading.Tasks.Task<bool> IzmeniKnjiguAsync(int id_knjige, Korisnik.ServiceReference1.Knjiga k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKorisnika", ReplyAction="http://tempuri.org/IOperater/IzmeniKorisnikaResponse")]
        bool IzmeniKorisnika(int id_korisnika, Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/IzmeniKorisnika", ReplyAction="http://tempuri.org/IOperater/IzmeniKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> IzmeniKorisnikaAsync(int id_korisnika, Korisnik.ServiceReference1.Korisnik k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PregledPorudzbina", ReplyAction="http://tempuri.org/IOperater/PregledPorudzbinaResponse")]
        Korisnik.ServiceReference1.Porudzbine[] PregledPorudzbina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PregledPorudzbina", ReplyAction="http://tempuri.org/IOperater/PregledPorudzbinaResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PregledPorudzbinaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/SviKorisnici", ReplyAction="http://tempuri.org/IOperater/SviKorisniciResponse")]
        Korisnik.ServiceReference1.Korisnik[] SviKorisnici();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/SviKorisnici", ReplyAction="http://tempuri.org/IOperater/SviKorisniciResponse")]
        System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik[]> SviKorisniciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PostaviPopust", ReplyAction="http://tempuri.org/IOperater/PostaviPopustResponse")]
        bool PostaviPopust(int id_knjige, float popust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperater/PostaviPopust", ReplyAction="http://tempuri.org/IOperater/PostaviPopustResponse")]
        System.Threading.Tasks.Task<bool> PostaviPopustAsync(int id_knjige, float popust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiKnjigu", ReplyAction="http://tempuri.org/IAdmin/ObrisiKnjiguResponse")]
        bool ObrisiKnjigu(int id_knjige);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiKnjigu", ReplyAction="http://tempuri.org/IAdmin/ObrisiKnjiguResponse")]
        System.Threading.Tasks.Task<bool> ObrisiKnjiguAsync(int id_knjige);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiKorisnika", ReplyAction="http://tempuri.org/IAdmin/ObrisiKorisnikaResponse")]
        bool ObrisiKorisnika(int id_korisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/ObrisiKorisnika", ReplyAction="http://tempuri.org/IAdmin/ObrisiKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> ObrisiKorisnikaAsync(int id_korisnika);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : Korisnik.ServiceReference1.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<Korisnik.ServiceReference1.IAdmin>, Korisnik.ServiceReference1.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Korisnik.ServiceReference1.Korisnik Prijava(string username, string password) {
            return base.Channel.Prijava(username, password);
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik> PrijavaAsync(string username, string password) {
            return base.Channel.PrijavaAsync(username, password);
        }
        
        public Korisnik.ServiceReference1.Knjiga[] SveKnjige() {
            return base.Channel.SveKnjige();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Knjiga[]> SveKnjigeAsync() {
            return base.Channel.SveKnjigeAsync();
        }
        
        public Korisnik.ServiceReference1.Porudzbine[] PorudzbineKorisnika(string id_korisnika) {
            return base.Channel.PorudzbineKorisnika(id_korisnika);
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PorudzbineKorisnikaAsync(string id_korisnika) {
            return base.Channel.PorudzbineKorisnikaAsync(id_korisnika);
        }
        
        public void PoruciKnjigu(Korisnik.ServiceReference1.Porudzbine p) {
            base.Channel.PoruciKnjigu(p);
        }
        
        public System.Threading.Tasks.Task PoruciKnjiguAsync(Korisnik.ServiceReference1.Porudzbine p) {
            return base.Channel.PoruciKnjiguAsync(p);
        }
        
        public void UnesiKnjigu(Korisnik.ServiceReference1.Knjiga k) {
            base.Channel.UnesiKnjigu(k);
        }
        
        public System.Threading.Tasks.Task UnesiKnjiguAsync(Korisnik.ServiceReference1.Knjiga k) {
            return base.Channel.UnesiKnjiguAsync(k);
        }
        
        public void UnesiKorisnika(Korisnik.ServiceReference1.Korisnik k) {
            base.Channel.UnesiKorisnika(k);
        }
        
        public System.Threading.Tasks.Task UnesiKorisnikaAsync(Korisnik.ServiceReference1.Korisnik k) {
            return base.Channel.UnesiKorisnikaAsync(k);
        }
        
        public bool IzmeniKnjigu(int id_knjige, Korisnik.ServiceReference1.Knjiga k) {
            return base.Channel.IzmeniKnjigu(id_knjige, k);
        }
        
        public System.Threading.Tasks.Task<bool> IzmeniKnjiguAsync(int id_knjige, Korisnik.ServiceReference1.Knjiga k) {
            return base.Channel.IzmeniKnjiguAsync(id_knjige, k);
        }
        
        public bool IzmeniKorisnika(int id_korisnika, Korisnik.ServiceReference1.Korisnik k) {
            return base.Channel.IzmeniKorisnika(id_korisnika, k);
        }
        
        public System.Threading.Tasks.Task<bool> IzmeniKorisnikaAsync(int id_korisnika, Korisnik.ServiceReference1.Korisnik k) {
            return base.Channel.IzmeniKorisnikaAsync(id_korisnika, k);
        }
        
        public Korisnik.ServiceReference1.Porudzbine[] PregledPorudzbina() {
            return base.Channel.PregledPorudzbina();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Porudzbine[]> PregledPorudzbinaAsync() {
            return base.Channel.PregledPorudzbinaAsync();
        }
        
        public Korisnik.ServiceReference1.Korisnik[] SviKorisnici() {
            return base.Channel.SviKorisnici();
        }
        
        public System.Threading.Tasks.Task<Korisnik.ServiceReference1.Korisnik[]> SviKorisniciAsync() {
            return base.Channel.SviKorisniciAsync();
        }
        
        public bool PostaviPopust(int id_knjige, float popust) {
            return base.Channel.PostaviPopust(id_knjige, popust);
        }
        
        public System.Threading.Tasks.Task<bool> PostaviPopustAsync(int id_knjige, float popust) {
            return base.Channel.PostaviPopustAsync(id_knjige, popust);
        }
        
        public bool ObrisiKnjigu(int id_knjige) {
            return base.Channel.ObrisiKnjigu(id_knjige);
        }
        
        public System.Threading.Tasks.Task<bool> ObrisiKnjiguAsync(int id_knjige) {
            return base.Channel.ObrisiKnjiguAsync(id_knjige);
        }
        
        public bool ObrisiKorisnika(int id_korisnika) {
            return base.Channel.ObrisiKorisnika(id_korisnika);
        }
        
        public System.Threading.Tasks.Task<bool> ObrisiKorisnikaAsync(int id_korisnika) {
            return base.Channel.ObrisiKorisnikaAsync(id_korisnika);
        }
    }
}
